### ISSUE TITLE
Form Errors on Mobile Need to be styled

### ISSUE THREAD

**Issue by m-henderson** [Pure-L0G1C/Notebook#1]
When entering invalid input into the form it let's you know by showing validation errors. These errors flow outside of the container on mobile device. 
Device: Pixel XL
Screenshot:
![image](https://user-images.githubusercontent.com/16070192/54077200-00013300-427b-11e9-8a86-82c90ea069f2.png)

**Comment by Bitwise-01** [comment]
I know, that’s what I was talking about, I’m fixing it

**Comment by m-henderson** [comment]
@Pure-L0G1C let me know when you put in a PR for it.

**Comment by m-henderson** [comment]
can I go ahead and close this one?

**Comment by Bitwise-01** [comment]
Yeah
