### ISSUE TITLE
WYSIWYG view the html content not the markup text 

### ISSUE THREAD

**Issue by al-sultani** [Pure-L0G1C/Notebook#2]
I colored a text and refreshed the page and got this: 

![myPic](https://user-images.githubusercontent.com/6137238/70392225-beaad900-19ee-11ea-8295-da6d27e5b749.png)

The WYSIWYG should view the marked-up text, not the HTML text. 

It is a very good tool BTW. 

Thanks

**Comment by Bitwise-01** [comment]
It should be fixed. Can you test it again?

**Comment by al-sultani** [comment]
@Pure-L0G1C  It works, however, the app is vulnerable to a security issue that I found while using the app.

**Comment by Bitwise-01** [comment]
Really? Join my Discord server at https://discord.gg/BTryaU

**Comment by al-sultani** [comment]
Fixed
